### ISSUE TITLE
getting code running and package installation errors

### ISSUE THREAD

**Issue by katyshelby** [katyshelby/TurtleRock_SAR#4]
Hey @tbuehrens 

Trying to get the first set of code to run where I can pull release code from RMIS for review.  Can't get it to work and getting some errors that indicate the Rtools and "need" packages need to be installed?  I've tried a bunch of different things but nothing seems to work...  here's some screen shots of the issue:

![package loading error](https://user-images.githubusercontent.com/78056375/127225158-435be8d0-ba0f-4c1b-84c5-2bcd1e945eac.jpg)

![Rtools and needs package](https://user-images.githubusercontent.com/78056375/127225921-bc082da3-6b0f-4a88-9ad5-7311a74fa8b0.jpg)

Also, I have some requests for additional data types to be added to this data pull.  I'll send an email with spreadsheet so we can discuss when we meet.

If you have time to meet some day this week would be great so I can atleast get this part of the code working.  I'm currently stuck until I can get this working.

**Comment by tbuehrens** [comment]
resolved 7/28 with commits to @katyshelby test local...unsure if they were pushed to test remote yet
